[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "neural-engine"
version = "0.0.1"
dependencies = [
    "torch>=2.1,<3.0",
    "numpy>=1.23",
]

[tool.setuptools.packages.find]
where = ["neural_engine"]


